name: noosphere_roast_client
description: A client library for ROAST threshold signatures
version: 3.0.0
repository: https://github.com/peercoin/noosphere_roast_client

environment:
  sdk: ^3.3.4

dependencies:
  coinlib: ^4.0.0
  frosty: ^3.0.0
  synchronized: ^3.1.0+1
  collection: ^1.17.1
  grpc: ^4.0.1
  protobuf: ^4.0.0
  yaml_edit: ^2.2.1
  yaml: ^3.1.2
  args: ^2.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
